### PR TITLE
BUG #26: fixing the internationalization flag

### LINKED ISSUE #26: The flag for the current language is not the correct
Pre requisites: 
- Browser with English configuration 

Steps: 
- Login with the user
- Look the current select language flag ( currently shows english as default ) but the whole app show spanish translations. 
Image

### PR DESCRIPTION
**Pull request by GusBauAr**

### CODE REVIEW

File: src/context/SidebarContext.jsx [hunk 1]
```diff
@@ -45,104 +41,125 @@ export const SidebarProvider = ({ children }) => {
...
-    const pathname = window?.location.pathname === '/login'
-
-    // if (pathname) return;
-    const defaultLang = globalSetting?.default_language || 'en'
-    const cookieLang = Cookies.get('i18next')
-    const currLang = Cookies.get('_currLang')
-
-    const removeRegion = (langCode) => langCode?.split('-')[0]
+    const pathnameIsLogin = window?.location.pathname === '/login'
+    if (pathnameIsLogin) {
```
Comment (Jhegs) [inline src/context/SidebarContext.jsx]: an if ( without logic inside ) doesn't make sense.

File: src/context/SidebarContext.jsx [hunk 2]
```diff
@@ -45,104 +41,125 @@ export const SidebarProvider = ({ children }) => {
...
+    if (i18n.language !== selectedLang) {
+      i18n.changeLanguage(selectedLang)
     }
 
-    // Change i18n language **only if it differs**
-    if (i18n.language !== selectedLang && !currLang) {
-      i18n.changeLanguage(selectedLang)
+    try {
+      Cookies.set('i18next', selectedLang, { sameSite: 'Lax' })
+    } catch {}
```
Comment (Jhegs) [inline src/context/SidebarContext.jsx]: catch without exception, ... that could be a warning in sonar. (even we not use it in this project.)

**Review by Jhegs — CHANGES_REQUESTED** [review]

**Review by Jhegs — APPROVED** [review]
